'use strict';
// Self-contained WebGL inspection renderer. No external CDN or source scripts.
(()=>{
 const get=id=>document.getElementById(id),canvas=get('geometrycanvas');
 let gl,program,batches=[],lineBatch=null,yaw=-.7,pitch=.15,zoom=3.3,drag=null,active=false,timer,ueTimer;
 const status=s=>get('decodestatus').textContent=s;
 async function request(path,body){const r=await fetch('api/decode/'+path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const data=await r.json();if(!r.ok)throw Error(data.error||r.status);return data;}
 const sub=(a,b)=>a.map((v,i)=>v-b[i]),dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],norm=a=>{const n=Math.hypot(...a)||1;return a.map(v=>v/n);};
 function shader(type,source){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;}
 function initialize(){if(gl)return;gl=canvas.getContext('webgl',{antialias:true});if(!gl)throw Error('WebGL 不可用；可使用 UE5 预览。');gl.getExtension('OES_element_index_uint');program=gl.createProgram();
 gl.attachShader(program,shader(gl.VERTEX_SHADER,`attribute vec3 p;attribute vec3 n;attribute vec2 uv;uniform mat4 matrix;varying vec3 normal;varying vec2 tex;void main(){gl_Position=matrix*vec4(p,1.);normal=n;tex=uv;}`));
 gl.attachShader(program,shader(gl.FRAGMENT_SHADER,`precision mediump float;uniform vec3 color;uniform bool checker;uniform bool lines;varying vec3 normal;varying vec2 tex;void main(){float light=lines?1.:.3+.7*abs(dot(normalize(normal),normalize(vec3(.5,-.8,.7))));float grid=checker?(.45+.55*mod(floor(tex.x*20.)+floor(tex.y*20.),2.)):1.;gl_FragColor=vec4(color*light*grid,1.);}`));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));gl.useProgram(program);gl.enable(gl.DEPTH_TEST);}
 function buffer(data,target=gl.ARRAY_BUFFER){const b=gl.createBuffer();gl.bindBuffer(target,b);gl.bufferData(target,data,gl.STATIC_DRAW);return b;}
 function release(){if(!gl)return;for(const b of batches)for(const x of b.buffers)gl.deleteBuffer(x);if(lineBatch)gl.deleteBuffer(lineBatch);lineBatch=null;batches=[];}
 function load(data){initialize();release();let lo=[Infinity,Infinity,Infinity],hi=[-Infinity,-Infinity,-Infinity];for(const m of data.meshes)for(const v of m.vertices)for(let a=0;a<3;a++){lo[a]=Math.min(lo[a],v[a]);hi[a]=Math.max(hi[a],v[a]);}
 const center=lo.map((v,a)=>(v+hi[a])/2),radius=Math.max(...hi.map((v,a)=>(v-lo[a])/2),1),scale=v=>v.map((x,a)=>(x-center[a])/radius);
 get('meshlist').replaceChildren();data.meshes.forEach((m,mi)=>{const normal=m.vertices.map(()=>[0,0,0]);for(const section of m.sections)for(let i=0;i<section.length;i+=3){const ids=section.slice(i,i+3),a=m.vertices[ids[0]],b=m.vertices[ids[1]],c=m.vertices[ids[2]],n=cross(sub(b,a),sub(c,a));for(const j of ids)for(let k=0;k<3;k++)normal[j][k]+=n[k];}
 const values=[];m.vertices.forEach((v,i)=>values.push(...scale(v),...norm(normal[i]),...m.uv[i]));const vb=buffer(new Float32Array(values));const batch={vb,buffers:[vb],sections:[],visible:true};m.sections.forEach((indices,si)=>{if(!indices.length)return;const edges=[];for(let i=0;i<indices.length;i+=3)edges.push(indices[i],indices[i+1],indices[i+1],indices[i+2],indices[i+2],indices[i]);const ib=buffer(new Uint32Array(indices),gl.ELEMENT_ARRAY_BUFFER),wb=buffer(new Uint32Array(edges),gl.ELEMENT_ARRAY_BUFFER);batch.buffers.push(ib,wb);batch.sections.push({ib,wb,count:indices.length,wcount:edges.length,color:[.42+.36*Math.sin(si*2+mi)**2,.5+.32*Math.sin(si*3+mi+1)**2,.5+.35*Math.sin(si+mi+2)**2]});});batches.push(batch);
 const label=document.createElement('label'),check=document.createElement('input');check.type='checkbox';check.checked=true;check.onchange=()=>{batch.visible=check.checked;draw();};label.append(check,document.createTextNode(m.name));get('meshlist').append(label);});
 const byName=new Map(data.skeleton.map(b=>[b.name,b])),lines=[];for(const bone of data.skeleton){const parent=byName.get(bone.parent);if(parent)for(const b of [bone,parent])lines.push(...scale(b.position),0,0,1,0,0);}lineBatch=buffer(new Float32Array(lines));lineBatch.vertexCount=lines.length/8;draw();}
 function bind(vb){gl.bindBuffer(gl.ARRAY_BUFFER,vb);for(const [name,size,offset]of [['p',3,0],['n',3,12],['uv',2,24]]){const a=gl.getAttribLocation(program,name);gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,size,gl.FLOAT,false,32,offset);}}
 function draw(){if(!gl||!active)return;const w=canvas.clientWidth,h=canvas.clientHeight;if(!w||!h)return;canvas.width=w*devicePixelRatio;canvas.height=h*devicePixelRatio;gl.viewport(0,0,canvas.width,canvas.height);gl.clearColor(.07,.085,.105,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);
 const eye=[Math.cos(yaw)*Math.cos(pitch)*zoom,Math.sin(yaw)*Math.cos(pitch)*zoom,Math.sin(pitch)*zoom],z=norm(eye),x=norm(cross([0,0,1],z)),y=cross(z,x),aspect=w/h,f=1.8,near=.01,far=30;
 const view=[x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,eye),-dot(y,eye),-dot(z,eye),1],proj=[f/aspect,0,0,0,0,f,0,0,0,0,(far+near)/(near-far),-1,0,0,2*far*near/(near-far),0],mat=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)for(let k=0;k<4;k++)mat[c*4+r]+=proj[k*4+r]*view[c*4+k];gl.uniformMatrix4fv(gl.getUniformLocation(program,'matrix'),false,mat);gl.uniform1i(gl.getUniformLocation(program,'checker'),get('uvcheck').checked);gl.uniform1i(gl.getUniformLocation(program,'lines'),get('wireframe').checked);
 for(const batch of batches){if(!batch.visible)continue;bind(batch.vb);for(const s of batch.sections){gl.uniform3fv(gl.getUniformLocation(program,'color'),s.color);const wire=get('wireframe').checked;gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,wire?s.wb:s.ib);gl.drawElements(wire?gl.LINES:gl.TRIANGLES,wire?s.wcount:s.count,gl.UNSIGNED_INT,0);}}
 if(get('showbones').checked&&lineBatch){gl.disable(gl.DEPTH_TEST);gl.uniform1i(gl.getUniformLocation(program,'lines'),1);gl.uniform1i(gl.getUniformLocation(program,'checker'),0);gl.uniform3f(gl.getUniformLocation(program,'color'),1,.75,.2);bind(lineBatch);gl.drawArrays(gl.LINES,0,lineBatch.vertexCount);gl.enable(gl.DEPTH_TEST);}}
 canvas.onpointerdown=e=>{drag=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId);};canvas.onpointerup=()=>drag=null;canvas.onpointermove=e=>{if(!drag)return;yaw-=(e.clientX-drag[0])*.008;pitch=Math.max(-1.45,Math.min(1.45,pitch+(e.clientY-drag[1])*.008));drag=[e.clientX,e.clientY];draw();};canvas.onwheel=e=>{e.preventDefault();zoom=Math.max(.2,Math.min(12,zoom*Math.exp(e.deltaY*.001)));draw();};canvas.onkeydown=e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-'].includes(e.key)){e.preventDefault();yaw+=e.key==='ArrowLeft'?.1:e.key==='ArrowRight'?-.1:0;pitch=Math.max(-1.45,Math.min(1.45,pitch+(e.key==='ArrowUp'?.1:e.key==='ArrowDown'?-.1:0)));zoom=Math.max(.2,Math.min(12,zoom+(e.key==='+'?-.2:e.key==='-'?.2:0)));draw();}};
 for(const id of ['wireframe','showbones','uvcheck'])get(id).onchange=draw;get('resetcamera').onclick=()=>{yaw=-.7;pitch=.15;zoom=3.3;draw();};new ResizeObserver(draw).observe(canvas);
 async function poll(){try{const s=await request('state');get('decodecancel').disabled=!s.running;get('sourcematerials').disabled=s.running;if(s.running){status(s.status==='materials'?'正在解析来源材质与贴图，生成 SourceMaterialIR…':'正在校验来源、解码并生成检查数据…');timer=setTimeout(poll,800);return;}if(s.status==='failed'||s.status==='cancelled'){status(s.error||'已取消');return;}const data=await request('result');status(data.errors.length?`部分解码失败：${data.errors.length} 项，见诊断`:'解码完成 · 静态检查预览');get('openue').disabled=!data.meshes.length;get('sourcematerials').disabled=!data.meshes.length;if(data.material_id)status(`来源材质已生成 · ${data.material_diagnostic_count} 条诊断 · 在 UE5 查看外观参考`);get('decodestats').textContent=`顶点 ${data.statistics.vertices.toLocaleString()}\n三角形 ${data.statistics.triangles.toLocaleString()}\n骨骼 ${data.statistics.bones}\n材质区 ${data.statistics.material_regions}\n直接 Morph ${data.statistics.morphs_applied}`;get('decodeissues').textContent=[...data.errors.map(e=>`${e.path}\n${e.message}`),...data.warnings].join('\n\n');get('decodefile').textContent=`本地检查数据：插件 Saved/Decoded/${data.decode_id}.ir.json`;if(data.source_material_ir){get('decodefile').textContent+='；材质 IR：'+data.source_material_ir;const material=await request('material-result');get('decodeissues').textContent+='\n\n来源材质诊断：\n'+material.diagnostics.map(d=>`${d.code} · ${JSON.stringify(d.source)}\n影响：${JSON.stringify(d.affected_bindings)}\n${d.impact}`).join('\n\n');}load(data);}catch(e){status(e.message);}}
 get('decode').onclick=async()=>{get('decodemodal').hidden=false;active=true;get('decodeclose').focus();get('openue').disabled=true;get('decodestats').textContent='';get('decodeissues').textContent='';release();draw();try{await request('start',{plan_id:planId});poll();}catch(e){status(e.message);}};
 get('decodeclose').onclick=()=>{get('decodemodal').hidden=true;active=false;clearTimeout(timer);get('decode').focus();};get('decodecancel').onclick=async()=>{await request('cancel',{});poll();};
 get('sourcematerials').onclick=async()=>{get('sourcematerials').disabled=true;get('openue').disabled=true;try{await request('materials',{});poll();}catch(e){status(e.message);get('sourcematerials').disabled=false;}};
 get('openue').onclick=async()=>{try{const r=await request('ue',{});status(r.message||'正在启动 UE5 临时检查窗口…');clearTimeout(ueTimer);async function check(){const s=await request('ue-state');if(s.status==='starting'){ueTimer=setTimeout(check,1500);return;}status((s.status==='ready'||s.status==='partial')?`UE5 已加载 · 材质 ${s.material_count||0} · ${(s.material_errors||[]).length} 项加载错误；来源着色近似与限制见材质诊断。`:s.error||s.status);}ueTimer=setTimeout(check,1500);}catch(e){status(e.message);}};
})();
